### ISSUE TITLE
Make flask-continuum depend on sqlalchemy_continuum

### ISSUE THREAD

**Issue by kettenbach-it** [bprinty/Flask-Continuum#12]
`pip install flask-continuum`

does not install `sqlalchemy_continuum`

which results in:

```
127.0.0.1 - - [28/Apr/2020 16:28:13] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/volker/PycharmProjects/verivinum-core-api/app.py", line 25, in <module>
    from flask_continuum import Continuum
  File "/Users/volker/PycharmProjects/verivinum-core-api/venv/lib/python3.7/site-packages/flask_continuum/__init__.py", line 11, in <module>
    from .mixins import VersioningMixin      ## noqa
  File "/Users/volker/PycharmProjects/verivinum-core-api/venv/lib/python3.7/site-packages/flask_continuum/mixins.py", line 11, in <module>
    from sqlalchemy_continuum import changeset, count_versions, is_modified
ModuleNotFoundError: No module named 'sqlalchemy_continuum'
```

Installing flask-continuum with pip should automatically install sqlalchemy_continuum

**Comment by bprinty** [comment]
Thanks for the heads up! I'll fix the issue and re-release as `0.1.7`.
